version: '2.1'
services:
    gis:
        image:
            xxx/test
        build: 
            context: .
        volumes:
            - .:/home/xxx/code
        working_dir:
            "/home/xxx/code"
        command: ["bash"]
        network_mode: "host"
