version: '2.1'
services:
    gis:
        image:
            xxx/test
        build: 
            context: .
        volumes:
            - ./scripts:/home/xxx/code/scripts
            - ../data:/home/xxx/code/data
            - ./notebooks:/home/xxx/code/notebooks
            - ./utils:/home/xxx/code/utils
        working_dir:
            "/home/xxx/code"
        command: ["bash"]
        network_mode: "host"
